# Explore Player Data

In [8]:
import pandas as pd

In [9]:
player_data = pd.read_csv('../data/players.csv')

In [10]:
player_data.head()

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,True,False,0.0,0.0,438098,0,0,-1,1,0,...,134,82,676,267,794,343,714,295,0.00,0.00
1,True,False,0.0,0.0,205651,0,0,-5,5,2,...,43,20,759,67,216,25,200,32,0.90,0.30
2,True,False,0.0,0.0,226597,0,0,1,-1,2,...,70,6,735,263,34,2,34,13,1.07,0.38
3,True,False,100.0,100.0,219847,0,0,-3,3,1,...,14,4,790,83,36,10,61,13,1.01,0.34
4,True,False,0.0,0.0,463748,0,0,0,0,0,...,667,53,106,36,619,68,643,71,0.00,0.00

The elements field contains data for each premier league player in the current season of FPL. We can access these data just like we would access data associated with a key in a dictionary. The response is a list of more dictionaries — one per player.

In [11]:
print(len(player_data.columns.tolist()))

103

In [12]:
player_data.describe()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
count,603.000000,603.000000,8.040000e+02,804.0,804.0,804.000000,804.000000,804.00000,804.000000,801.000000,...,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000
mean,60.613599,59.369818,2.818805e+06,0.0,0.0,-1.054726,1.054726,0.51990,2.620647,1.148315,...,402.500000,129.185323,402.500000,129.185323,402.500000,129.185323,402.500000,129.185323,0.593209,0.133619
std,48.496035,48.388663,1.553934e+07,0.0,0.0,2.070847,2.070847,1.15363,0.897830,1.924675,...,232.239101,96.225823,232.239101,96.225823,232.239101,96.225823,232.239101,96.225823,0.493506,0.162207
min,0.000000,0.000000,1.515700e+04,0.0,0.0,-8.000000,-13.000000,0.00000,1.000000,-1.500000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,0.000000,0.000000,1.900880e+05,0.0,0.0,-2.000000,0.000000,0.00000,2.000000,0.000000,...,201.750000,46.000000,201.750000,46.000000,201.750000,46.000000,201.750000,46.000000,0.000000,0.000000
50%,100.000000,100.000000,4.301425e+05,0.0,0.0,-1.000000,1.000000,0.00000,3.000000,0.200000,...,402.500000,107.000000,402.500000,107.000000,402.500000,107.000000,402.500000,107.000000,0.870000,0.040000
75%,100.000000,100.000000,5.084160e+05,0.0,0.0,0.000000,2.000000,1.00000,3.000000,2.000000,...,603.250000,207.250000,603.250000,207.250000,603.250000,207.250000,603.250000,207.250000,1.020000,0.260000
max,100.000000,100.000000,1.000539e+08,0.0,0.0,13.000000,8.000000,12.00000,5.000000,11.800000,...,804.000000,347.000000,804.000000,347.000000,804.000000,347.000000,804.000000,347.000000,1.820000,1.070000

In [13]:
player_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Columns: 103 entries, can_transact to clean_sheets_per_90
dtypes: bool(6), float64(33), int64(54), object(10)
memory usage: 614.1+ KB

In [14]:
df = player_data[['web_name', 'goals_scored', 'assists']]

df.sort_values(by=['goals_scored', 'assists'], ascending=False)

    web_name  goals_scored  assists
464  M.Salah            29       18
574     Isak            23        6
493  Haaland            22        3
135   Mbeumo            20        9
624     Wood            20        3
..       ...           ...      ...
797   Edozie             0        0
798  Okoduwa             0        0
800  Pereira             0        0
801    Djiga             0        0
803     Mané             0        0

[804 rows x 3 columns]

In [18]:
player_data.columns.tolist()

['can_transact',
 'can_select',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'code',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'id',
 'in_dreamteam',
 'news',
 'news_added',
 'now_cost',
 'photo',
 'points_per_game',
 'removed',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'region',
 'team_join_date',
 'birth_date',
 'has_temporary_code',
 'opta_code',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'starts',
 'expected_goals',
 'expected_assists',
 'expected_goal_involvements',
 'expected_goals_conceded',
 'mng_win',
 'mng_draw',
 'mng_loss',
 'mng_underdog_win',
 'mng_underdog_draw',
 'mng_clean_sheets',
 'mng_goals_scored',
 'influence_rank',
 'influence_rank_type',
 'creativity_rank',
 'creativity_rank_type',
 'threat_rank',
 'threat_rank_type',
 'ict_index_rank',
 'ict_index_rank_type',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'penalties_order',
 'penalties_text',
 'expected_goals_per_90',
 'saves_per_90',
 'expected_assists_per_90',
 'expected_goal_involvements_per_90',
 'expected_goals_conceded_per_90',
 'goals_conceded_per_90',
 'now_cost_rank',
 'now_cost_rank_type',
 'form_rank',
 'form_rank_type',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'selected_rank',
 'selected_rank_type',
 'starts_per_90',
 'clean_sheets_per_90']

In [19]:
# Get player data from 'elements' field
players = player_data['element_type']
#The elements field contains data for each premier league player in the current season of FPL. We can access these data just like we would access data associated with a key in a dictionary. The response is a list of more dictionaries — one per player.
players.head()

0    3
1    4
2    2
3    4
4    1
Name: element_type, dtype: int64

In [20]:
# Show all columns without truncation
pd.set_option('display.max_columns', None)

player_data

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,ep_this,event_points,first_name,form,id,in_dreamteam,news,news_added,now_cost,photo,points_per_game,removed,second_name,selected_by_percent,special,squad_number,status,team,team_code,total_points,transfers_in,transfers_in_event,transfers_out,transfers_out_event,value_form,value_season,web_name,region,team_join_date,birth_date,has_temporary_code,opta_code,minutes,goals_scored,assists,clean_sheets,goals_conceded,own_goals,penalties_saved,penalties_missed,yellow_cards,red_cards,saves,bonus,bps,influence,creativity,threat,ict_index,starts,expected_goals,expected_assists,expected_goal_involvements,expected_goals_conceded,mng_win,mng_draw,mng_loss,mng_underdog_win,mng_underdog_draw,mng_clean_sheets,mng_goals_scored,influence_rank,influence_rank_type,creativity_rank,creativity_rank_type,threat_rank,threat_rank_type,ict_index_rank,ict_index_rank_type,corners_and_indirect_freekicks_order,corners_and_indirect_freekicks_text,direct_freekicks_order,direct_freekicks_text,penalties_order,penalties_text,expected_goals_per_90,saves_per_90,expected_assists_per_90,expected_goal_involvements_per_90,expected_goals_conceded_per_90,goals_conceded_per_90,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,True,False,0.0,0.0,438098,0,0,-1,1,0,3,0.0,0.0,0,Fábio,0.0,1,False,Has joined Portuguese side FC Porto on loan fo...,2024-08-29T11:06:25.241953Z,54,438098.jpg,0.0,False,Ferreira Vieira,0.0,False,NaN,u,1,3,0,439,0,2825,0,0.0,0.0,Fábio Vieira,NaN,NaN,NaN,False,p438098,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0.00,0.00,0.00,0.00,0,0,0,0,0,0,0,795,343,795,343,791,341,795,343,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.00,0.00,0.00,0.00,134,82,676,267,794,343,714,295,0.00,0.00
1,True,False,0.0,0.0,205651,0,0,-5,5,2,4,0.0,0.0,0,Gabriel,0.0,2,False,Knee injury - Expected back 01 Jun,2025-01-12T22:00:07.802845Z,65,205651.jpg,2.5,False,Fernando de Jesus,1.0,False,NaN,i,1,3,42,1238437,0,1409940,0,0.0,6.5,G.Jesus,30.0,2022-07-04,1997-04-03,False,p205651,600,3,2,2,5,0,0,0,4,0,0,6,152,154.4,119.5,255.0,52.6,6,3.05,0.52,3.57,5.82,0,0,0,0,0,0,0,349,33,276,31,134,32,287,33,NaN,NaN,NaN,NaN,NaN,NaN,0.46,0.0,0.08,0.54,0.87,0.75,43,20,759,67,216,25,200,32,0.90,0.30
2,True,False,0.0,0.0,226597,0,0,1,-1,2,2,0.0,0.0,0,Gabriel,0.0,3,False,Hamstring injury - Expected back 01 Jun,2025-04-01T22:00:07.982867Z,61,226597.jpg,4.2,False,dos Santos Magalhães,12.2,False,NaN,i,1,3,117,5093448,0,5431768,0,0.0,19.2,Gabriel,30.0,2020-09-01,1997-12-19,False,p226597,2363,3,2,10,22,0,0,0,4,0,0,9,459,584.6,208.8,287.0,108.2,28,2.70,1.21,3.91,23.09,0,0,0,0,0,0,0,108,40,202,45,120,11,135,36,NaN,NaN,NaN,NaN,NaN,NaN,0.10,0.0,0.05,0.15,0.88,0.84,70,6,735,263,34,2,34,13,1.07,0.38
3,True,False,100.0,100.0,219847,0,0,-3,3,1,4,1.5,1.5,1,Kai,0.0,4,False,NaN,2025-02-12T09:00:08.755570Z,77,219847.jpg,4.2,False,Havertz,6.2,False,NaN,a,1,3,97,2644355,0,3530099,0,0.0,12.6,Havertz,80.0,2023-06-28,1999-06-11,False,p219847,1872,9,3,7,20,0,0,0,5,0,0,14,343,467.6,269.0,711.0,144.8,21,9.53,1.65,11.18,19.32,0,0,0,0,0,0,0,155,18,161,18,34,15,81,17,NaN,NaN,NaN,NaN,3.0,NaN,0.46,0.0,0.08,0.54,0.93,0.96,14,4,790,83,36,10,61,13,1.01,0.34
4,True,False,0.0,0.0,463748,0,0,0,0,0,1,0.0,0.0,0,Karl,0.0,5,False,Loaned to Real Valladolid,2024-08-14T08:31:46.556082Z,40,463748.jpg,0.0,False,Hein,0.0,False,NaN,u,1,3,0,0,0,4643,0,0.0,0.0,Hein,NaN,NaN,NaN,False,p463748,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0.00,0.00,0.00,0.00,0,0,0,0,0,0,0,612,68,599,57,558,38,612,68,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.00,0.00,0.00,0.00,667,53,106,36,619,68,643,71,0.00,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
799,True,False,100.0,100.0,516939,0,0,0,0,0,2,3.5,0.0,2,Emmanuel,0.0,720,False,NaN,2025-02-17T10:00:10.280621Z,40,516939.jpg,2.8,False,Agbadou,0.4,False,NaN,a,20,39,45,76487,0,30459,0,0.0,11.2,Agbadou,54.0,2025-01-09,1997-06-17,False,p516939,1410,1,0,4,22,0,0,0,3,0,0,1,223,395.2,57.3,67.0,52.0,16,0.90,0.32,1.22,23.12,0,0,0,0,0,0,0,184,68,351,117,314,98,290,87,NaN,NaN,NaN,NaN,NaN,NaN,0.06,0.0,0.02,0.08,1.48,1.40,687,197,126,67,161,45,276,107,1.02,0.26
800,True,False,NaN,NaN,100040854,0,0,0,0,0,5,3.2,0.0,9,Vítor Manuel,0.0,751,False,NaN,NaN,8,100040854.jpg,0.0,False,de Oliveira Lopes Pereira,2.3,False,NaN,a,20,39,111,104766,0,45027,0,0.0,138.8,Pereira,173.0,2024-12-19,1968-07-26,False,man40855,0,0,0,0,0,0,0,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0,0.00,0.00,0.00,0.00,8,2,6,2,1,5,22,557,7,535,7,486,7,557,7,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.00,0.00,0.00,0.00,796,12,7,7,567,7,689,16,0.00,0.00
801,True,False,NaN,NaN,531170,0,0,0,0,0,2,0.0,0.0,0,Nasser,0.0,769,False,NaN,NaN,45,531170.jpg,0.8,False,Djiga,0.0,False,NaN,a,20,39,4,1745,0,1066,0,0.0,0.9,Djiga,35.0,2025-02-03,2002-11-15,False,p531170,65,0,0,0,2,0,0,0,0,0,0,0,11,5.6,2.1,0.0,0.8,1,0.00,0.01,0.01,1.23,0,0,0,0,0,0,0,512,183,492,181,713,266,529,185,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.01,0.01,1.70,2.77,442,76,391,210,540,183,685,235,1.38,0.00
802,True,False,100.0,100.0,433312,0,0,0,0,0,3,2.0,0.0,9,Marshall,0.0,770,False,NaN,2025-03-09T23:00:09.898129Z,50,433312.jpg,3.6,False,Munetsi,0.1,False,NaN,a,20,39,50,33865,0,28115,0,0.0,10.0,Munetsi,239.0,2025-02-03,1996-06-22,False,p433312,1077,2,2,5,11,0,0,0,0,0,0,4,134,176.8,132.9,212.0,52.3,12,3.32,1.08,4.39,14.59,0,0,0,0,0,0,0,332,150,265,164,166,106,289,150,NaN,NaN,NaN,NaN,NaN,NaN,0.28,0.0,0.09,0.37,1.22,0.92,216,135,593,217,82,37,532,201,1.00,0.42
803,True,False,NaN,NaN,647671,0,0,0,0,0,4,0.2,0.0,0,Mateus,0.0,784,False,NaN,NaN,45,647671.jpg,1.0,False,Mané,0.1,False,NaN,a,20,39,1,8678,0,4474,0,0.0,0.2,Mané,241.0,2025-02-24,2007-09-16,False,p647671,1,0,0,0,0,0,0,0,0,0,0,0,3,0.0,0.3,0.0,0.0,0,0.00,0.00,0.00,0.00,0,0,0,0,0,0,0,770,74,515,56,753,74,770,74,NaN,NaN,NaN,NaN,NaN,NaN,0.00,0.0,0.00,0.00,0.00,0.00,494,83,443,24,509,58,547,74,0.00,0.00