# Explore Player Data

In [2]:
import pandas as pd

In [4]:
player_data = pd.read_csv('../data/players.csv')

In [5]:
player_data.head()

,can_transact,can_select,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
0,True,False,0.0,0.0,438098,0,0,-1,1,0,...,134,82,676,267,794,343,714,295,0.00,0.00
1,True,False,0.0,0.0,205651,0,0,-5,5,2,...,43,20,759,67,216,25,200,32,0.90,0.30
2,True,False,0.0,0.0,226597,0,0,1,-1,2,...,70,6,735,263,34,2,34,13,1.07,0.38
3,True,False,100.0,100.0,219847,0,0,-3,3,1,...,14,4,790,83,36,10,61,13,1.01,0.34
4,True,False,0.0,0.0,463748,0,0,0,0,0,...,667,53,106,36,619,68,643,71,0.00,0.00

The elements field contains data for each premier league player in the current season of FPL. We can access these data just like we would access data associated with a key in a dictionary. The response is a list of more dictionaries — one per player.

In [15]:
player_data.columns.tolist()

['can_transact',
 'can_select',
 'chance_of_playing_next_round',
 'chance_of_playing_this_round',
 'code',
 'cost_change_event',
 'cost_change_event_fall',
 'cost_change_start',
 'cost_change_start_fall',
 'dreamteam_count',
 'element_type',
 'ep_next',
 'ep_this',
 'event_points',
 'first_name',
 'form',
 'id',
 'in_dreamteam',
 'news',
 'news_added',
 'now_cost',
 'photo',
 'points_per_game',
 'removed',
 'second_name',
 'selected_by_percent',
 'special',
 'squad_number',
 'status',
 'team',
 'team_code',
 'total_points',
 'transfers_in',
 'transfers_in_event',
 'transfers_out',
 'transfers_out_event',
 'value_form',
 'value_season',
 'web_name',
 'region',
 'team_join_date',
 'birth_date',
 'has_temporary_code',
 'opta_code',
 'minutes',
 'goals_scored',
 'assists',
 'clean_sheets',
 'goals_conceded',
 'own_goals',
 'penalties_saved',
 'penalties_missed',
 'yellow_cards',
 'red_cards',
 'saves',
 'bonus',
 'bps',
 'influence',
 'creativity',
 'threat',
 'ict_index',
 'starts',
 'expected_goals',
 'expected_assists',
 'expected_goal_involvements',
 'expected_goals_conceded',
 'mng_win',
 'mng_draw',
 'mng_loss',
 'mng_underdog_win',
 'mng_underdog_draw',
 'mng_clean_sheets',
 'mng_goals_scored',
 'influence_rank',
 'influence_rank_type',
 'creativity_rank',
 'creativity_rank_type',
 'threat_rank',
 'threat_rank_type',
 'ict_index_rank',
 'ict_index_rank_type',
 'corners_and_indirect_freekicks_order',
 'corners_and_indirect_freekicks_text',
 'direct_freekicks_order',
 'direct_freekicks_text',
 'penalties_order',
 'penalties_text',
 'expected_goals_per_90',
 'saves_per_90',
 'expected_assists_per_90',
 'expected_goal_involvements_per_90',
 'expected_goals_conceded_per_90',
 'goals_conceded_per_90',
 'now_cost_rank',
 'now_cost_rank_type',
 'form_rank',
 'form_rank_type',
 'points_per_game_rank',
 'points_per_game_rank_type',
 'selected_rank',
 'selected_rank_type',
 'starts_per_90',
 'clean_sheets_per_90']

In [13]:
player_data.describe()

,chance_of_playing_next_round,chance_of_playing_this_round,code,cost_change_event,cost_change_event_fall,cost_change_start,cost_change_start_fall,dreamteam_count,element_type,ep_next,...,now_cost_rank,now_cost_rank_type,form_rank,form_rank_type,points_per_game_rank,points_per_game_rank_type,selected_rank,selected_rank_type,starts_per_90,clean_sheets_per_90
count,603.000000,603.000000,8.040000e+02,804.0,804.0,804.000000,804.000000,804.00000,804.000000,801.000000,...,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000,804.000000
mean,60.613599,59.369818,2.818805e+06,0.0,0.0,-1.054726,1.054726,0.51990,2.620647,1.148315,...,402.500000,129.185323,402.500000,129.185323,402.500000,129.185323,402.500000,129.185323,0.593209,0.133619
std,48.496035,48.388663,1.553934e+07,0.0,0.0,2.070847,2.070847,1.15363,0.897830,1.924675,...,232.239101,96.225823,232.239101,96.225823,232.239101,96.225823,232.239101,96.225823,0.493506,0.162207
min,0.000000,0.000000,1.515700e+04,0.0,0.0,-8.000000,-13.000000,0.00000,1.000000,-1.500000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000
25%,0.000000,0.000000,1.900880e+05,0.0,0.0,-2.000000,0.000000,0.00000,2.000000,0.000000,...,201.750000,46.000000,201.750000,46.000000,201.750000,46.000000,201.750000,46.000000,0.000000,0.000000
50%,100.000000,100.000000,4.301425e+05,0.0,0.0,-1.000000,1.000000,0.00000,3.000000,0.200000,...,402.500000,107.000000,402.500000,107.000000,402.500000,107.000000,402.500000,107.000000,0.870000,0.040000
75%,100.000000,100.000000,5.084160e+05,0.0,0.0,0.000000,2.000000,1.00000,3.000000,2.000000,...,603.250000,207.250000,603.250000,207.250000,603.250000,207.250000,603.250000,207.250000,1.020000,0.260000
max,100.000000,100.000000,1.000539e+08,0.0,0.0,13.000000,8.000000,12.00000,5.000000,11.800000,...,804.000000,347.000000,804.000000,347.000000,804.000000,347.000000,804.000000,347.000000,1.820000,1.070000

In [14]:
player_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 804 entries, 0 to 803
Columns: 103 entries, can_transact to clean_sheets_per_90
dtypes: bool(6), float64(33), int64(54), object(10)
memory usage: 614.1+ KB

In [22]:
df = player_data[['web_name', 'goals_scored', 'assists']]

df.sort_values(by=['goals_scored', 'assists'], ascending=False)

    web_name  goals_scored  assists
464  M.Salah            29       18
574     Isak            23        6
493  Haaland            22        3
135   Mbeumo            20        9
624     Wood            20        3
..       ...           ...      ...
797   Edozie             0        0
798  Okoduwa             0        0
800  Pereira             0        0
801    Djiga             0        0
803     Mané             0        0

[804 rows x 3 columns]

In [ ]:
# Get player data from 'elements' field
players = player_data['elements']
The elements field contains data for each premier league player in the current season of FPL. We can access these data just like we would access data associated with a key in a dictionary. The response is a list of more dictionaries — one per player.
players.head()

KeyError: 'elements'